Menu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.urls')),
    path('', include('meals.urls')),
]

urlpatterns.append(path('static/<path:path>', never_cache(serve)))
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

api/urls.py
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from django.urls import path, include
from .views import ApiMealViewSet


router = DefaultRouter()
router.register('meals', ApiMealViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
 ]

meals/urls.py
from django.urls import path

from .views import MealsListView, OrderView

app_name = 'meals'

urlpatterns = [
    path('', MealsListView.as_view(), name='index'),
    path('create_order/', OrderView.as_view(), name='create_order'),
]

meals/models.py
from django.db import models
from django.core import validators


class Allergens(models.Model):
    """Аллергены"""

    name = models.CharField("Название", max_length=30, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Аллерген'
        verbose_name_plural = 'Аллергены'


class Category(models.Model):
    """Категории"""

    name = models.CharField('Название категории', max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Meals(models.Model):
    """Блюда"""

    name = models.CharField("Название", max_length=30, db_index=True, unique=True)
    proteins = models.PositiveSmallIntegerField("Белки", validators=[validators.MaxValueValidator(10000)])
    fats = models.PositiveSmallIntegerField("Жиры", validators=[validators.MaxValueValidator(10000)])
    carbohydrates = models.PositiveSmallIntegerField("Углеводы", validators=[validators.MaxValueValidator(10000)])
    calories = models.PositiveSmallIntegerField(verbose_name="Калории")
    price = models.DecimalField("Стоимость", max_digits=7, decimal_places=2, default=100,
                                validators=[validators.MinValueValidator(0)])
    picture = models.ImageField("Изображение", null=True, blank=True)
    allergens = models.ManyToManyField(Allergens, verbose_name='Аллергены')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

api/views.py
from meals.models import Meals
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated

from .serializers import MealSerializer


class ApiMealViewSet(ModelViewSet):
    """CRUD информации о блюде из меню"""

    queryset = Meals.objects.all()
    serializer_class = MealSerializer
    permission_classes = (IsAuthenticated,)

meals/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from .models import Meals, Category
from .service import get_order_info


class MealsListView(ListView):
    """Вывод списка блюд"""

    context_object_name = 'meals'
    model = Meals

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        return context


class OrderView(View):
    """
    Вывод информации о заказе:
    - сумма заказа
    - список заказанных блюд
    - список аллергенов, которые содержаться в выбранных блюдах
    """

    def post(self, request):
        data = request.POST
        context = get_order_info(data)
        return render(request, 'meals/order.html', context)

templates/meals/meals_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type"
          content="text/html; charset=utf-8">
    <title> Меню </title>
    <style type="text/css">
        table {
            border-collapse: collapse;
        }

        th, td {
            padding: 5px 5px 5px 5px;
            border: solid black;
            text-align: center
        }

    </style>

</head>
<header>
    <h1> Меню </h1>
</header>
<body>
<div>
    <form method="post" action={% url 'meals:create_order' %}>
        {% csrf_token %}
        {% for category in categories %}
            <h2>{{ category }} </h2>
            <table>
                <tr>
                    <th rowspan="2" width="50" scope="col"> Название блюда</th>
                    <th width="10" colspan="4"> Пищевая ценность</th>
                    <th rowspan="2" width="80" scope="col"> Цена</th>
                    <th rowspan="2" width="100" scope="col"> Аллергены</th>
                    <th rowspan="2" width="100" scope="col"> Изображение</th>
                    <th rowspan="2" width="30" scope="col"> -</th>
                </tr>
                <tr>
                    <th scope="col"> Белки</th>
                    <th scope="col"> Жиры</th>
                    <th scope="col"> Углеводы</th>
                    <th scope="col"> Калории</th>
                </tr>
                {% for meal in meals %}
                    {% if category.id == meal.category.id %}
                        <tr>
                            <td>{{ meal.name }}</td>
                            <td>{{ meal.proteins }}</td>
                            <td>{{ meal.fats }}</td>
                            <td>{{ meal.carbohydrates }}</td>
                            <td>{{ meal.calories }}</td>
                            <td>{{ meal.price }}</td>
                            <td> {% for allergen in meal.allergens.all %}
                                {{ allergen.name }}
                            {% endfor %}</td>
                            <td>{% if meal.picture %}
                                <img src="{{ meal.picture.url }}" width="80" height="80">
                            {% endif %}
                            </td>
                            <td><input id="meal_name" type="checkbox"
                                       name="{{ meal.name }}" value="{{ meal.name }}"></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
        {% endfor %}
        <p><input type="submit" value="Сохранить"></p>

    </form>
</div>
</body>
</html>

templates/meals/order.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type"
        content="text/html; charset=utf-8">
        <title> Меню </title>
    </head>
    <header>
        <h1> Ваш заказ </h1>
    </header>
    <body>
        <div>
            <h2>Сумма заказа: {{ price }} </h2>
            <h2>В заказ входят следующие блюда:</h2>
            {% for meal in order %}
                <ul> {{ meal}} </ul>
            {% endfor %}

            <h2>Блюда данного заказа содержат следующие аллергены:</h2>
            {% for allergen in allergens %}
                <ul>{{ allergen}}</ul>
            {% endfor %}
        </div>
    </body>
</html>